steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      - "build"
      - "--build-arg=AUTH0_DOMAIN=${_AUTH0_DOMAIN}"
      - "--build-arg=AUTH0_CLIENT_ID=${_AUTH0_CLIENT_ID}"
      - "--build-arg=APP_BASE_URL=${_APP_BASE_URL}"
      - "--build-arg=AUTH0_ISSUER_BASE_URL=${_AUTH0_ISSUER_BASE_URL}"
      - "--build-arg=AUTH0_CLIENT_ID_MGMT=${_AUTH0_CLIENT_ID_MGMT}"
      - "--build-arg=AUTH0_CLIENT_SECRET"
      - "--build-arg=AUTH0_CLIENT_SECRET_MGMT"
      - "--build-arg=AUTH0_SECRET"
      - "--tag=gcr.io/$PROJECT_ID/${_REPO_NAME}/app:${_COMMIT_SHA}"
      - "."
    secretEnv:
      - "AUTH0_CLIENT_SECRET"
      - "AUTH0_CLIENT_SECRET_MGMT"
      - "AUTH0_SECRET"

substitutions:
  _AUTH0_DOMAIN: "genai.atko.rocks"
  _AUTH0_CLIENT_ID: "QUrWaaJDIVw8CkbmubzOSIuR1AvqX07a"
  _APP_BASE_URL: "https://chatbot.atko.rocks"
  _AUTH0_ISSUER_BASE_URL: "https://genai-8794913713030954.us.auth0.com"
  _AUTH0_CLIENT_ID_MGMT: "QUrWaaJDIVw8CkbmubzOSIuR1AvqX07a"
  _REPO_NAME: "cloudbuild"
  _COMMIT_SHA: "manual"

availableSecrets:
  secretManager:
    - versionName: projects/$PROJECT_ID/secrets/a0-chatbot-client-secret/versions/latest
      env: "AUTH0_CLIENT_SECRET"
    - versionName: projects/$PROJECT_ID/secrets/a0-chatbot-client-secret-mgmt/versions/latest
      env: "AUTH0_CLIENT_SECRET_MGMT"
    - versionName: projects/$PROJECT_ID/secrets/a0-chatbot-encrypt-secret/versions/latest
      env: "AUTH0_SECRET"

images:
  - "gcr.io/$PROJECT_ID/${_REPO_NAME}/app:${_COMMIT_SHA}"
