name: ✨ Feature Request
description: Suggest a new feature or improvement
title: "[Feature] "
labels: [feature]
body:
  - type: textarea
    id: idea
    attributes:
      label: What would you like to see?
      description: Describe the feature you'd like added or improved.
      placeholder: "I'd like a dark mode toggle..."

  - type: textarea
    id: benefit
    attributes:
      label: Why is this useful?
      description: Explain how this feature will improve the app for users.
      placeholder: "It helps users work better at night..."
