name: PR Title Lint

on:
  pull_request:
    types: [opened, edited, synchronize, reopened]

jobs:
  lint-pr-title:
    runs-on: ubuntu-latest
    steps:
      - uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            refactor
            test
            style
          scopes: |
            auth
            calendar
            files
            mail
            ui
            ci
            deps
            ai
            infra
          requireScope: true
          requireSubject: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
